### ISSUE TITLE
Add the ability to load entire directories of embeddings files to avoid --file for each one.

### ISSUE THREAD

**Issue by kainazzzo** [kainazzzo/GPT-CLI#9]
```bash
gpt --prompt "generate documentation for XYZ feature" --directory=./embeds
```

This would load multiple embed.dat files that you put in the folder. Scripts can be used to call gpt embed, but I could see wanting to do this too:

```bash
gpt embed --directory ~/code/ --extension cs
```

This issue is just for the first example.

**Comment by Sigauri** [comment]
Hello. 

Just wanted to make sure. This is supposed to embed all the .cs files in `~/code/` , right?  
`gpt embed --directory ~/code/ --extension cs`

**Comment by kainazzzo** [comment]
Not exactly. The ```gpt embed``` command reads STDIN and produces an embedding document to STDOUT. The only options there are for --chunk-size. Pipe the standard output to another command or redirect it to a file to load it later. Once you get an embedding saved (e.g. to embed.dat) you would do:
```shell
gpt chat --directory ~/codeEmbeds/ --file ~/otherEmbeds/embed.dat --model=gpt-4
```

This will load the entire ~/codeEmbeds/ folder and another file ~/otherEmbeds/embed.dat if they're in the embeddings format. It attempts to deserialize a specific document format and skips files that aren't embeds.

Once you load embeds that way, they become searchable in this gptcli session
